### ISSUE TITLE
home

### ISSUE THREAD

**Issue by enricoinyourlife** [In-Your-Life/grandeprato.it#3]
togliamo la e con l'apostrofo e mettiamo la e accentata,
![image](https://user-images.githubusercontent.com/72559537/109623609-9b150680-7b3d-11eb-8593-f65fa25c41eb.png)

il certificato di Trip è vecchio di tre anni, facciamoci dare uno più aggiornato
![image](https://user-images.githubusercontent.com/72559537/109623163-25109f80-7b3d-11eb-84a1-9c0bfcb9fca5.png)
anche qua ci vuole la solita frasetta alternativa al form contatti
![image](https://user-images.githubusercontent.com/72559537/109623709-b6801180-7b3d-11eb-9d38-b98c29d6b093.png)

**Comment by nicola-iyl** [comment]
corretto
