### ISSUE TITLE
tags title

### ISSUE THREAD

**Issue by enricoinyourlife** [In-Your-Life/grandeprato.it#4]
nessuna foto della gallery si ingrandisce, è corretto sia così?

mi sa che per i tags c'è stata un po' di confusione? a febbraio mi avevi chiesto di riepilogarti i tags da mettere pagina per pagina ma non mi pare sia cos, te li riporto di seguito
per l'italiano

url a piacere

meta name keywords quelle attuali su tutte le pagine

meta name description quelle attuali su tutte le pagine

per questa pagina http://bozze.inyourlife.info/il_grande_prato/index.html riprendiamo il title  della pagina https://www.grandeprato.it/

per la pagina http://bozze.inyourlife.info/il_grande_prato/gallery.html  title di https://www.grandeprato.it/fotogallery_ita.php

per la pagina http://bozze.inyourlife.info/il_grande_prato/virtual-tour.html title di https://www.grandeprato.it/appartamento_agriturismo_firenze.htm

per la pagina http://bozze.inyourlife.info/il_grande_prato/contatti.html title di https://www.grandeprato.it/agriturismo_dintorni_firenze.htm

per l'inglese

url a piacere

meta name keywords quelle attuali su tutte le pagine

meta name description quelle attuali su tutte le pagine

per la home title  di https://www.grandeprato.it/farm_holidays_tuscany.htm

per la pagina gallery title di https://www.grandeprato.it/farmhouse_accommodation_tuscany.htm

per la pagina virtual tour title di https://www.grandeprato.it/fotogallery_en.php

per la pagina contatti title di https://www.grandeprato.it/agritourism_tuscany.htm

**Comment by nicola-iyl** [comment]
corretti
